/*
 * This source file was generated by the Gradle 'init' task
 */
package com.esportstournamentscheduler.CLI;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test@SuppressWarnings("unused")
 void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
